/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUniversitiesRouteImport } from './routes/admin/universities'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as EmployeeApplicationsRouteImport } from './routes/employee/applications'
import { Route as EmployeeDashboardRouteImport } from './routes/employee/dashboard'
import { Route as EmployeeDocumentsRouteImport } from './routes/employee/documents'
import { Route as EmployeeLeadsRouteImport } from './routes/employee/leads'
import { Route as EmployeePaymentsRouteImport } from './routes/employee/payments'
import { Route as EmployeeProfileRouteImport } from './routes/employee/profile'
import { Route as EmployeeUniversitiesRouteImport } from './routes/employee/universities'
import { Route as StudentUploadTokenRouteImport } from './routes/student-upload.$token'
import { Route as AdminEmployeesIndexRouteImport } from './routes/admin/employees/index'
import { Route as AdminEmployeesIdRouteImport } from './routes/admin/employees/$id'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminStudentsIdRouteImport } from './routes/admin/students/$id'
import { Route as AdminStudentsNewRouteImport } from './routes/admin/students/new'
import { Route as EmployeeStudentsIndexRouteImport } from './routes/employee/students/index'
import { Route as EmployeeStudentsIdRouteImport } from './routes/employee/students/$id'
import { Route as EmployeeStudentsNewRouteImport } from './routes/employee/students/new'
import { Route as AdminStudentsIdEditRouteImport } from './routes/admin/students/$id.edit'
import { Route as EmployeeStudentsIdEditRouteImport } from './routes/employee/students/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUniversitiesRoute = AdminUniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeApplicationsRoute = EmployeeApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeDocumentsRoute = EmployeeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLeadsRoute = EmployeeLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeePaymentsRoute = EmployeePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeUniversitiesRoute = EmployeeUniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => EmployeeRoute,
} as any)
const StudentUploadTokenRoute = StudentUploadTokenRouteImport.update({
  id: '/student-upload/$token',
  path: '/student-upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesIdRoute = AdminEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsNewRoute = AdminStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeeStudentsIndexRoute = EmployeeStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeStudentsIdRoute = EmployeeStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeStudentsNewRoute = EmployeeStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminStudentsIdEditRoute = AdminStudentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminStudentsIdRoute,
} as any)
const EmployeeStudentsIdEditRoute = EmployeeStudentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EmployeeStudentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/employee/applications': typeof EmployeeApplicationsRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/leads': typeof EmployeeLeadsRoute
  '/employee/payments': typeof EmployeePaymentsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/universities': typeof EmployeeUniversitiesRoute
  '/student-upload/$token': typeof StudentUploadTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRouteWithChildren
  '/admin/students/new': typeof AdminStudentsNewRoute
  '/employee/students/$id': typeof EmployeeStudentsIdRouteWithChildren
  '/employee/students/new': typeof EmployeeStudentsNewRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/employee/students/': typeof EmployeeStudentsIndexRoute
  '/admin/students/$id/edit': typeof AdminStudentsIdEditRoute
  '/employee/students/$id/edit': typeof EmployeeStudentsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/employee/applications': typeof EmployeeApplicationsRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/leads': typeof EmployeeLeadsRoute
  '/employee/payments': typeof EmployeePaymentsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/universities': typeof EmployeeUniversitiesRoute
  '/student-upload/$token': typeof StudentUploadTokenRoute
  '/admin': typeof AdminIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRouteWithChildren
  '/admin/students/new': typeof AdminStudentsNewRoute
  '/employee/students/$id': typeof EmployeeStudentsIdRouteWithChildren
  '/employee/students/new': typeof EmployeeStudentsNewRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/employee/students': typeof EmployeeStudentsIndexRoute
  '/admin/students/$id/edit': typeof AdminStudentsIdEditRoute
  '/employee/students/$id/edit': typeof EmployeeStudentsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/employee/applications': typeof EmployeeApplicationsRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/leads': typeof EmployeeLeadsRoute
  '/employee/payments': typeof EmployeePaymentsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/universities': typeof EmployeeUniversitiesRoute
  '/student-upload/$token': typeof StudentUploadTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRouteWithChildren
  '/admin/students/new': typeof AdminStudentsNewRoute
  '/employee/students/$id': typeof EmployeeStudentsIdRouteWithChildren
  '/employee/students/new': typeof EmployeeStudentsNewRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/employee/students/': typeof EmployeeStudentsIndexRoute
  '/admin/students/$id/edit': typeof AdminStudentsIdEditRoute
  '/employee/students/$id/edit': typeof EmployeeStudentsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/employee'
    | '/login'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/leads'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/universities'
    | '/employee/applications'
    | '/employee/dashboard'
    | '/employee/documents'
    | '/employee/leads'
    | '/employee/payments'
    | '/employee/profile'
    | '/employee/universities'
    | '/student-upload/$token'
    | '/admin/'
    | '/employee/'
    | '/admin/employees/$id'
    | '/admin/students/$id'
    | '/admin/students/new'
    | '/employee/students/$id'
    | '/employee/students/new'
    | '/admin/employees/'
    | '/admin/students/'
    | '/employee/students/'
    | '/admin/students/$id/edit'
    | '/employee/students/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/leads'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/universities'
    | '/employee/applications'
    | '/employee/dashboard'
    | '/employee/documents'
    | '/employee/leads'
    | '/employee/payments'
    | '/employee/profile'
    | '/employee/universities'
    | '/student-upload/$token'
    | '/admin'
    | '/employee'
    | '/admin/employees/$id'
    | '/admin/students/$id'
    | '/admin/students/new'
    | '/employee/students/$id'
    | '/employee/students/new'
    | '/admin/employees'
    | '/admin/students'
    | '/employee/students'
    | '/admin/students/$id/edit'
    | '/employee/students/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/employee'
    | '/login'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/leads'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/universities'
    | '/employee/applications'
    | '/employee/dashboard'
    | '/employee/documents'
    | '/employee/leads'
    | '/employee/payments'
    | '/employee/profile'
    | '/employee/universities'
    | '/student-upload/$token'
    | '/admin/'
    | '/employee/'
    | '/admin/employees/$id'
    | '/admin/students/$id'
    | '/admin/students/new'
    | '/employee/students/$id'
    | '/employee/students/new'
    | '/admin/employees/'
    | '/admin/students/'
    | '/employee/students/'
    | '/admin/students/$id/edit'
    | '/employee/students/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
  LoginRoute: typeof LoginRoute
  StudentUploadTokenRoute: typeof StudentUploadTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/universities': {
      id: '/admin/universities'
      path: '/universities'
      fullPath: '/admin/universities'
      preLoaderRoute: typeof AdminUniversitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/applications': {
      id: '/employee/applications'
      path: '/applications'
      fullPath: '/employee/applications'
      preLoaderRoute: typeof EmployeeApplicationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/dashboard': {
      id: '/employee/dashboard'
      path: '/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/documents': {
      id: '/employee/documents'
      path: '/documents'
      fullPath: '/employee/documents'
      preLoaderRoute: typeof EmployeeDocumentsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/leads': {
      id: '/employee/leads'
      path: '/leads'
      fullPath: '/employee/leads'
      preLoaderRoute: typeof EmployeeLeadsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/payments': {
      id: '/employee/payments'
      path: '/payments'
      fullPath: '/employee/payments'
      preLoaderRoute: typeof EmployeePaymentsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/universities': {
      id: '/employee/universities'
      path: '/universities'
      fullPath: '/employee/universities'
      preLoaderRoute: typeof EmployeeUniversitiesRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/student-upload/$token': {
      id: '/student-upload/$token'
      path: '/student-upload/$token'
      fullPath: '/student-upload/$token'
      preLoaderRoute: typeof StudentUploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees/$id': {
      id: '/admin/employees/$id'
      path: '/employees/$id'
      fullPath: '/admin/employees/$id'
      preLoaderRoute: typeof AdminEmployeesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$id': {
      id: '/admin/students/$id'
      path: '/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/new': {
      id: '/admin/students/new'
      path: '/students/new'
      fullPath: '/admin/students/new'
      preLoaderRoute: typeof AdminStudentsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employee/students/': {
      id: '/employee/students/'
      path: '/students'
      fullPath: '/employee/students/'
      preLoaderRoute: typeof EmployeeStudentsIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/students/$id': {
      id: '/employee/students/$id'
      path: '/students/$id'
      fullPath: '/employee/students/$id'
      preLoaderRoute: typeof EmployeeStudentsIdRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/students/new': {
      id: '/employee/students/new'
      path: '/students/new'
      fullPath: '/employee/students/new'
      preLoaderRoute: typeof EmployeeStudentsNewRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/students/$id/edit': {
      id: '/admin/students/$id/edit'
      path: '/edit'
      fullPath: '/admin/students/$id/edit'
      preLoaderRoute: typeof AdminStudentsIdEditRouteImport
      parentRoute: typeof AdminStudentsIdRoute
    }
    '/employee/students/$id/edit': {
      id: '/employee/students/$id/edit'
      path: '/edit'
      fullPath: '/employee/students/$id/edit'
      preLoaderRoute: typeof EmployeeStudentsIdEditRouteImport
      parentRoute: typeof EmployeeStudentsIdRoute
    }
  }
}

interface AdminStudentsIdRouteChildren {
  AdminStudentsIdEditRoute: typeof AdminStudentsIdEditRoute
}

const AdminStudentsIdRouteChildren: AdminStudentsIdRouteChildren = {
  AdminStudentsIdEditRoute: AdminStudentsIdEditRoute,
}

const AdminStudentsIdRouteWithChildren = AdminStudentsIdRoute._addFileChildren(
  AdminStudentsIdRouteChildren,
)

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUniversitiesRoute: typeof AdminUniversitiesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmployeesIdRoute: typeof AdminEmployeesIdRoute
  AdminStudentsIdRoute: typeof AdminStudentsIdRouteWithChildren
  AdminStudentsNewRoute: typeof AdminStudentsNewRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUniversitiesRoute: AdminUniversitiesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEmployeesIdRoute: AdminEmployeesIdRoute,
  AdminStudentsIdRoute: AdminStudentsIdRouteWithChildren,
  AdminStudentsNewRoute: AdminStudentsNewRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployeeStudentsIdRouteChildren {
  EmployeeStudentsIdEditRoute: typeof EmployeeStudentsIdEditRoute
}

const EmployeeStudentsIdRouteChildren: EmployeeStudentsIdRouteChildren = {
  EmployeeStudentsIdEditRoute: EmployeeStudentsIdEditRoute,
}

const EmployeeStudentsIdRouteWithChildren =
  EmployeeStudentsIdRoute._addFileChildren(EmployeeStudentsIdRouteChildren)

interface EmployeeRouteChildren {
  EmployeeApplicationsRoute: typeof EmployeeApplicationsRoute
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeDocumentsRoute: typeof EmployeeDocumentsRoute
  EmployeeLeadsRoute: typeof EmployeeLeadsRoute
  EmployeePaymentsRoute: typeof EmployeePaymentsRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeUniversitiesRoute: typeof EmployeeUniversitiesRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  EmployeeStudentsIdRoute: typeof EmployeeStudentsIdRouteWithChildren
  EmployeeStudentsNewRoute: typeof EmployeeStudentsNewRoute
  EmployeeStudentsIndexRoute: typeof EmployeeStudentsIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeApplicationsRoute: EmployeeApplicationsRoute,
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeDocumentsRoute: EmployeeDocumentsRoute,
  EmployeeLeadsRoute: EmployeeLeadsRoute,
  EmployeePaymentsRoute: EmployeePaymentsRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeUniversitiesRoute: EmployeeUniversitiesRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  EmployeeStudentsIdRoute: EmployeeStudentsIdRouteWithChildren,
  EmployeeStudentsNewRoute: EmployeeStudentsNewRoute,
  EmployeeStudentsIndexRoute: EmployeeStudentsIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
  LoginRoute: LoginRoute,
  StudentUploadTokenRoute: StudentUploadTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
